networks:
  hls-network:
    driver: bridge

services:
  app:
    container_name: hls-app
    image: pestler/nodejs2024q3-service:app
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    networks:
      - hls-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

  postgres:
    container_name: hls-postgres
    image: pestler/nodejs2024q3-service:postgres
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - hls-network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  postgres_logs:
