services:
  postgres:
    image: postgres:latest
    container_name: home_library_db_container_2025
    env_file: .env
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_logs:/var/log/postgresql
    networks:
      - app_network

  app:
    #image: pestler/nodejs2025q2-service-app:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: home_library_app_container_2025
    env_file: .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - postgres
    develop:
      watch:
      - action: sync+restart
        path: ./src
        target: /app/src
        ignore:
          - node_modules
    restart: always
    volumes:
      - logs_data:/app/logs
      - node_modules:/app/node_modules

    networks:
      - app_network

volumes:
  postgres_data:
  postgres_logs:
  logs_data:
  node_modules:

networks:
  app_network:
    driver: bridge
